version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: mydb
    volumes: 
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetx
  web:
    image: nginx:latest
    container_name: mynginx
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - mynetx

volumes:
  db_data:

networks:
  mynetx:    
    driver: bridge 